
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for SSH Tunnel with Custom Payload and Proxy
LUCI_DEPENDS:=+luci-base +sshtunnel +corkscrew
PKG_NAME:=luci-app-customtunnel
PKG_VERSION:=1.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
